### ISSUE TITLE
`--cache` flag isn't working as expected

### ISSUE THREAD

**Issue by mbtamuli** [EasyEngine/site-type-wp#50]
1. `--cache` flag currently doesn't enable object-cache as mentioned in this issue - https://github.com/EasyEngine/easyengine/issues/1221
2. `--cache` flag enables Nginx page cache, but doesn't provide a mechanism to evict cached pages when the content has been modified, something like https://wordpress.org/plugins/nginx-helper/

**Comment by renatonascalves** [comment]
To allow more flexibility, do you think something like `--cache=object` or `--cache=page` can be added?

There are those that might want page cache, and others, the object one.

**Comment by pjv** [comment]
fixing number 1 (object cache) means installing an object cache plugin in the site. I use and recommend this one: https://wordpress.org/plugins/redis-cache/. I contributed code for that plugin that allows the site admin to purge the object cache for a given site without affecting the object cache for other sites using the same redis store. Other redis-backed object caches just blow the whole redis db away to purge the cache.

in my one brief test of the page cache (ee v4 beta6), i did not see any page caching happening. I looked at a test post in a not-logged-in, no comment-cookie browser window, then made a change to that post in a different browser that was logged in and then reloaded the page in the non-logged-in browser and i saw the change i made to the post. That indicates to me that the page was either never cached or that nginx is not correctly retrieving from the cache.

**Comment by kirtangajjar** [comment]
> To allow more flexibility, do you think something like --cache=object or --cache=page can be added?
@renatonascalves Yes that is in the pipeline :smile:

**Comment by rahul286** [comment]
@pjv re: https://wordpress.org/plugins/redis-cache/
Can you please go through - https://github.com/EasyEngine/easyengine/issues/1082 ?

**Comment by mrrobot47** [comment]
Closing this issue as it has been taken care of in PR https://github.com/EasyEngine/site-type-wp/pull/51
