### ISSUE TITLE
Define WP_CACHE_KEY_SALT on redis site creation

### ISSUE THREAD

**Issue by kirtangajjar** [EasyEngine/site-type-wp#66]
~We need to add following line in `wp-config.php` to ensure cache key of one site do not conflict with cache key of other sites~ - 
```
define('WP_CACHE_KEY_SALT', 'site_name');
```
and we also set cache ttl on cache as we do in ee3 - 
```
define('WP_REDIS_MAXTTL', 14400);
```

Edit: `WP_CACHE_KEY_SALT` is already set by wp-cli. we just need to add max TTL.

**Comment by mrrobot47** [comment]
@kirtangajjar Please comment on https://github.com/EasyEngine/site-type-wp/pull/51 PR for the same. `WP_CACHE_KEY_SALT` is already there. TTL can be added.

**Comment by mrrobot47** [comment]
Closing this as it has been taken care of in PR https://github.com/EasyEngine/site-type-wp/pull/51
