### ISSUE TITLE
Please disregard

### ISSUE THREAD

**Issue by b167er** [EasyEngine/site-type-wp#91]
I posted this issue in the wrong category, and have edited this as I cannot delete it.

**Comment by mrrobot47** [comment]
@b167er this was the right place to create the issue: https://github.com/EasyEngine/easyengine/issues/1263

This is the repository that handles changes and issues related to WordPress site type for the site-command.

As far as deleting goes, you don't need to delete it. Just closing an accidentally opened issue or a solved issue is good enough.
